import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import { Provider } from "../utils/Provider";
import Footer from "@/app/components/footer";
import MainContainer from "../components/main-container";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      {" "}
      <body className="">
        <MainContainer>
          <Provider>
            <div className="flex h-screen flex-col justify-between font-poppins">
              <Navbar />
              <main className="mb-auto">{children}</main>
              <Footer />
            </div>
          </Provider>
        </MainContainer>
      </body>
    </html>
  );
}
