import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import { Provider } from "../utils/Provider";
import Footer from "@/components/footer";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} h-full bg-background mx-auto max-w-7xl sm:px-6 lg:px-8`}
      >
        <Provider>
          <div className=" h-screen mx-auto max-w-4xl sm:px-6 lg:px-8">
            <Navbar />
            <main className="flex-1 mx-auto bg-accent">{children}</main>
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
